#pragma config(Sensor, S1,     lightSensor,    sensorLightActive)
#pragma config(Motor,  motorA,          leftMotor,     tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**********************************************
 * Lab 3 : Starter code
 * Written by Kaushik Viswanathan,
 * Modified by Allan Wang (Jan 2017)

 * Feel free to modify any part of these codes.
 **********************************************/

//Global variables - you will need to change some of these
//Robot's positions
float robot_X = 0.0, robot_Y = 0.0, robot_TH = 0.0;

int velocityUpdateInterval = 5;
int PIDUpdateInterval = 2;

//Change these during demo
int inputStraight[2] = {10, 0}; // in mm
int inputTurn[2] = {0, 0}; // in degrees, negative means clockwise rotation
int motorPower = 50;

/*****************************************
 * Complete this function so that it
 * continuously updates the robot's position
 *****************************************/
task dead_reckoning()
{

	while(1)
	{
		//
		// Fill in code for numerical integration / position estimation here
		//

		/*Code that plots the robot's current position and also prints it out as text*/
		nxtSetPixel(50 + (int)(100.0 * robot_X), 32 + (int)(100.0 * robot_Y));
		nxtDisplayTextLine(0, "X: %f", robot_X);
		nxtDisplayTextLine(1, "Y: %f", robot_Y);
		nxtDisplayTextLine(2, "t: %f", robot_TH);

		wait1Msec(velocityUpdateInterval);
	}
}

/*****************************************
 * Function that draws a grid on the LCD
 * for easier readout of whatever is plot
 *****************************************/
void draw_grid()
{
	for(int i = 0; i < 65; i++)
	{
		nxtSetPixel(50, i);
		int grid5 = (i - 32) % 5;
		int grid10 = (i - 32) % 10;
		if(!grid5 && grid10)
		{
			for(int j = -2; j < 3; j++)
			{
				nxtSetPixel(50 + j, i);
			}
		}
		else if(!grid10)
		{
			for(int j = -4; j < 5; j++)
			{
				nxtSetPixel(50 + j, i);
			}
		}
	}
	for(int i = 0; i < 101; i++)
	{
		nxtSetPixel(i, 32);
		int grid5 = (i - 100) % 5;
		int grid10 = (i - 100) % 10;
		if(!grid5 && grid10)
		{
			for(int j = -2; j < 3; j++)
			{
				nxtSetPixel(i, 32 + j);
			}
		}
		else if(!grid10)
		{
			for(int j = -4; j < 5; j++)
			{
				nxtSetPixel(i, 32 + j);
			}
		}
	}
}

/**********************************************
 * Function that judges if two floats are equal
 **********************************************/
 bool equal(float a, float b) {
   float epsilon = 1;
   if (abs(a-b) < epsilon) {
     return true;
   } else {
     return false;
   }
 }

float distToDegrees(float dist) {
	return dist * 0.1470 * 360.0;
}

float capMotor(float m) {
	if (m > 80) {
		return 80;
	}
	else if (m < -80) {
		return 80;
	}
	else {
		return m;
	}
}
/*****************************************
 * Main function - Needs changing
 *****************************************/
task main()
{
	/* Reset encoders and turn on PID control */
	nMotorEncoder[motorB] = 0;
	nMotorEncoder[motorC] = 0;
	nMotorPIDSpeedCtrl[motorB] = mtrSpeedReg;
	nMotorPIDSpeedCtrl[motorC] = mtrSpeedReg;
	nPidUpdateInterval = PIDUpdateInterval;

	int goalStraight = 0;
	int goalTurn = 0;
	float start_X = 0;
	float start_Y = 0;
	float distTravelled = 0;

	draw_grid();
	startTask(dead_reckoning);

	//for(int i = 0; i < 2; i++)
	//{
	//	goalStraight = inputStraight[i];
	//	goalTurn = inputTurn[i];

	//	//
	//	// Write your own codes for turning
	//	//

	//	start_X = robot_X;
	//	start_Y = robot_Y;

	//	motor[motorA] = motorPower;
	//	motor[motorB] = motorPower;

	//	distTravelled = sqrt(pow(robot_X - start_X, 2) + pow(robot_Y - start_Y, 2));

	//	while (nMotorEncoder[leftWheel] < 360) {

	//		distTravelled = sqrt(pow(robot_X - start_X, 2) + pow(robot_Y - start_Y, 2));
	//	}

	//}
	float angle1 = -90;
	float dist1 = 10;
	float angle2 = -45;
	float dist2 = 15;

  float opposite = 1;
	if(angle1 < 0) opposite = -1;
	float  turnLen = angle1 * 250/90;
	while(abs(nMotorEncoder[leftMotor]) < abs(turnLen)){
		motor[leftMotor] = opposite * 50;
		motor[rightMotor] = opposite * -50;
	}

	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;
	float wheels = (nMotorEncoder[leftMotor] + nMotorEncoder[rightMotor]) / 2.0;
	while(wheels < distToDegrees(dist1)) {
		wheels = (nMotorEncoder[leftMotor] + nMotorEncoder[rightMotor]) / 2.0;
		float p = 0.5;
		float left = p * (distToDegrees(dist1) - nMotorEncoder[leftMotor]);
		float right = p * (distToDegrees(dist1) - nMotorEncoder[rightMotor]);
		float turnP = 0.5;
		motor[leftMotor] = capMotor(left) - turnP * (nMotorEncoder[leftMotor] - nMotorEncoder[rightMotor]);
		motor[rightMotor] = capMotor(right) + turnP * (nMotorEncoder[leftMotor] - nMotorEncoder[rightMotor]);
		writeDebugStreamLine("%d, %d", nMotorEncoder[leftMotor], nMotorEncoder[rightMotor]);
	}

	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;

	float opposite1 = 1;
	if(angle2 < 0) opposite1 = -1;
	float  turnLen1 = angle2 * 250/90;
	while(abs(nMotorEncoder[leftMotor]) < abs(turnLen1)){
		motor[leftMotor] = opposite1 * 50;
		motor[rightMotor] = opposite1 * -50;
	}

	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;

		while(wheels < distToDegrees(dist2)) {
		wheels = (nMotorEncoder[leftMotor] + nMotorEncoder[rightMotor]) / 2.0;
		float p = 0.5;
		float left = p * (distToDegrees(dist2) - nMotorEncoder[leftMotor]);
		float right = p * (distToDegrees(dist2) - nMotorEncoder[rightMotor]);
		float turnP = 0.5;
		motor[leftMotor] = capMotor(left) - turnP * (nMotorEncoder[leftMotor] - nMotorEncoder[rightMotor]);
		motor[rightMotor] = capMotor(right) + turnP * (nMotorEncoder[leftMotor] - nMotorEncoder[rightMotor]);
		writeDebugStreamLine("%d, %d", nMotorEncoder[leftMotor], nMotorEncoder[rightMotor]);
	}

	motor[motorA] = 0;
	motor[motorB] = 0;
	nNxtButtonTask  = 0;
	while(nNxtButtonPressed != kExitButton) {}
}
