#pragma config(Sensor, S1,     frontSensor,    sensorSONAR)
#pragma config(Sensor, S2,     sideSensor,     sensorTouch)
#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int leftTurns = 0;
task main()
{
	// Motors are reversed to drive backwards.
	while(true) {
		if (SensorValue[frontSensor] < 15) {
			leftTurns = leftTurns + 1;
			motor[leftMotor] = -20;
			motor[rightMotor] = -20;
			wait1Msec(500);
			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
			wait1Msec(200);
			if (leftTurns < 8) {
				motor[leftMotor] = -20;
				motor[rightMotor] = 20;
			}
			else {
				motor[leftMotor] = 20;
				motor[rightMotor] = -20;
			}
			wait1Msec(1200);
		}
		else {
			motor[leftMotor] = 20;
			motor[rightMotor] = 20;
		}
	}

}
