#pragma config(Motor,  motorA,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("joystickSimple");
#include "JoystickDriver.c"

task main()
{
	while(true) {
		getJoystickSettings(joystick);
		float forward = joystick.joy1_y1;
		float turn = joystick.joy1_x2;
		float left = forward + turn;
		float right = forward - turn;

		if(abs(left) > 20) {
			motor[leftMotor] = left;
		}
		else motor[leftMotor] = 0;
		if(abs(right) > 20) {
			motor[rightMotor] = right;
		}
		else motor[rightMotor] = 0;

	}
}
