#pragma config(Sensor, S1,     frontSensor,    sensorLightActive)
#pragma config(Sensor, S2,     backSensor,     sensorLightActive)
#pragma config(Motor,  motorB,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int BALANCED = 50;
int BACK_OFFSET = 12;
int p = 8;
int d = 15;

task main()
{
	int prevError = 0;
	while(true) {
		int front = SensorValue(frontSensor);
		int back = SensorValue(backSensor) + BACK_OFFSET;
		int motorOutput = 0;
		int curError = 0;
		int diff = 0;
		if (front > BALANCED) {
			curError = front - BALANCED;
			diff = curError - prevError;
			motorOutput = (front - BALANCED) * p + diff * d;
			prevError = curError;
		}
		else {
			curError = back - BALANCED;
			diff = curError - prevError;
			motorOutput = -((back - BALANCED) * p + diff * d);
			prevError = curError;
		}

 		motor[leftMotor] = motorOutput;
		motor[rightMotor] = motorOutput;

		writeDebugStreamLine("Front: %d, Back: %d", front, back);

	}
}
