#pragma config(Sensor, S1,     frontSensor,    sensorLightActive)
#pragma config(Sensor, S2,     backSensor,     sensorLightActive)
#pragma config(Motor,  motorB,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int p = 60;
int d = 0;

int NUM_VALUES = 3;
int averaging[3];
task main()
{
	float prevError = 0;
	//while(nNxtButtonPressed != kEnterButton) {}
	int correction = SensorValue(frontSensor) - SensorValue(backSensor);
	correction = 6;
	int count = 0;
	while(true) {

		int front = SensorValue(frontSensor);
		int back = SensorValue(backSensor) + correction;
		int motorOutput = 0;
		float curError = 0;
		float diff = 0;

		float total = 0;
		averaging[count] = front - back;
		for(int i = 0; i < NUM_VALUES; i++){
			total += averaging[i];
		}
		curError = total / (float) NUM_VALUES;
		//curError = front - back;

		diff = curError - prevError;
		motorOutput = curError * p + diff * d;
		prevError = curError;

 		motor[leftMotor] = motorOutput;
		motor[rightMotor] = motorOutput;

	  writeDebugStreamLine("%f", curError);
		count++;
		count = count % NUM_VALUES;
	}
}
